# Generated by Django 5.0.7 on 2024-11-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_tweet_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
