# Generated by Django 5.0.7 on 2024-11-03 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_tweet_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='content',
        ),
    ]
